# This is a basic workflow to help you get started with Actions

name: API Doc Release Manually

on:
  workflow_dispatch:
    inputs:
      releaseCycle:
        default: 'release'
        description: 'Determined which release cycle the doc will be published to. Available options are : "alpha", "beta" and "release"'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install

      - name: build
        run: |
          yarn build:document

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: echo version
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ref:${{github.event.inputs.releaseCycle}}

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ref:${{github.event.inputs.releaseCycle}}
          run: |
            echo ${{ steps.docker_build.outputs.digest }}
