# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [feature/typedoc]
  pull_request:
    branches: [feature/typedoc]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install

      - name: build
        run: |
          yarn build:document

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: extract packagejson # Writes version into ${{ env.PACKAGE_VERSION }}
        uses: nyaa8/package-version@v1.0.3
        with:
          path: 'package.json'
          follow-symlinks: 'false'

      - name: is this cycle alpha
        if: contains(env.PACKAGE_VERSION, 'alpha')
        run: echo "RELEASE_CYCLE=alpha" >> $GITHUB_ENV

      - name: is this cycle beta
        if: contains(env.PACKAGE_VERSION, 'beta')
        run: echo "RELEASE_CYCLE=beta" >> $GITHUB_ENV

      - name: is this cycle release
        if: true && !contains(env.PACKAGE_VERSION, 'beta') && !contains(env.PACKAGE_VERSION, 'alpha')
        run: echo "RELEASE_CYCLE=release" >> $GITHUB_ENV

      - name: echo release cycle
        run: echo "$RELEASE_CYCLE"
      # - name: checkout repo
      #   uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ref:latest

      # - name: Run the image in a container
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: ${{ secrets.DOCKERHUB_USERNAME }}/ref:latest
      #     run: |
      #       echo ${{ steps.docker_build.outputs.digest }}
